# Generated by Django 5.0.2 on 2024-04-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0026_appuser_is_verified_appuser_otp_delete_demataccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='otp',
            new_name='otp_token',
        ),
        migrations.AddField(
            model_name='appuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
