# Generated by Django 5.0.2 on 2024-04-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0027_rename_otp_appuser_otp_token_appuser_otp_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='otp_token',
            new_name='otp',
        ),
    ]
