# Generated by Django 5.0.2 on 2024-04-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0028_rename_otp_token_appuser_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='otp',
            new_name='otp_token',
        ),
    ]
